Feature/87 login system
Funfunz/lumina-next pull request #110
Opened 2024-09-16 20:36 UTC by AdrianaAC

CSS to be reviewed - not normalized to Lumina yet.

2024-09-17 23:16 UTC, JWebCoder requested changes
- A lot is still needed, there should be no global element target on CSS
- All classes need to be prefixed with "lumina_"
- Use the token variables for our list to set the correct colors
- Fixe the change between the multiple screens
- The logic by the isLoggedIn should only affect the editor mode
- Our package does not support css.modules, please use the BEM approach we are doing
- remove the unwanted files
- remove the changes from tsconfig.app.json

2024-09-17 23:16 UTC, JWebCoder commented on examples/vite-react/tsconfig.app.json
> +    "../../packages/lumina-core/src/components/login/login.tsx",
please remove this new lines

2024-09-18 08:56 UTC, AdrianaAC commented
> * A lot is still needed, there should be no global element target on CSS - [solved]
> * All classes need to be prefixed with "lumina_" - [solved]
> * Use the token variables for our list to set the correct colors - [solved]
> * Fixe the change between the multiple screens
> * The logic by the isLoggedIn should only affect the editor mode
> * Our package does not support css.modules, please use the BEM approach we are doing - [solved]
> * remove the unwanted files - [solved]
> * remove the changes from tsconfig.app.json - [solved]

2024-09-19 15:21 UTC, AdrianaAC commented
Fix the change between the multiple screens - [solved]
The logic by the isLoggedIn should only affect the editor mode - [solved]
navigation now working

To do: 
general components to lumina components
re-use styling

2024-09-20 00:02 UTC, AdrianaAC commented
General components replaced by Lumina components.

To do: 
Fix login page styles
Re-use styles
<form> replaced by <Form/> from Lumina

2024-09-20 09:38 UTC, AdrianaAC commented
Styles as figma. Styles re-used on all 3 pages. 

To do:
should <form> be a <Form> by Lumina?

2024-09-20 15:25 UTC, JWebCoder approved these changes

2024-09-20 15:25 UTC, merged