feature/58-forms
Funfunz/lumina-next pull request #30
Opened 2024-07-30 14:49 UTC by bmirra01

- Implementation of "react-form-component"
- Adaptation of this already pre-built component by adding in the <Form> wrapper some of our own components, hence creating the <LumForm>

...WIP...

Trello Ticket:
[https://trello.com/c/Bw8RUBVr/58-forms](url)

2024-08-05 16:31 UTC, bmirra01 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Forms](https://trello.com/c/Bw8RUBVr/58-forms)

2024-08-07 12:26 UTC, JWebCoder requested changes
besides the issues on the PR, please create a component for each form element that already includes the required classname to render the correct layout.

2024-08-07 12:26 UTC, JWebCoder commented on package.json
> +    "react-form-component": "^2.6.6"
remove this from the main project

2024-08-07 12:26 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/packageExample/formExample.scss
what is this for?

2024-08-07 12:26 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/packageExample/formExample.tsx
what is this for?

2024-08-07 12:26 UTC, JWebCoder commented on packages/lumina-core/src/components/sidebar/index.tsx
> +    panel: (
all this needs to be removed before the PR is merged

2024-08-07 12:58 UTC, bmirra01 commented on package.json
> +    "react-form-component": "^2.6.6"
Done

2024-08-07 14:00 UTC, JWebCoder requested changes

2024-08-07 14:00 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/checkbox/index.tsx
> +  [key: string]: any
is it possible to extend the props from the package instead of this "any"?

2024-08-07 15:41 UTC, bmirra01 commented
@JWebCoder  done.

2024-08-07 16:28 UTC, Felix-by-merkle requested changes
And why the React class component. it's 2024 not 2015

2024-08-07 16:28 UTC, Felix-by-merkle commented on packages/lumina-core/src/components/form-components/checkbox/index.tsx
> +    const className = this.props.className || 'lum__checkbox'
why one or the other? either I style everything or I use the existing styles?
it should extend the existing styles and allow to be styled

2024-08-07 16:28 UTC, Felix-by-merkle commented on packages/lumina-core/src/components/form-components/input/index.tsx
> +    const className = this.props.className || 'lum__input'
same as above

2024-08-07 16:28 UTC, Felix-by-merkle commented on packages/lumina-core/src/components/form-components/radio-button/index.tsx
> +    const className = this.props.className || 'lum__radio-button'
same

2024-08-07 16:28 UTC, Felix-by-merkle commented on packages/lumina-core/src/components/form-components/slider/index.tsx
> +    const className = this.props.className || 'lum__slider'
same

2024-08-07 16:28 UTC, Felix-by-merkle commented on packages/lumina-core/src/components/form-components/switch-list/index.tsx
> +    const className = this.props.className || 'lum__switch-list'
same

2024-08-07 16:28 UTC, Felix-by-merkle commented on packages/lumina-core/src/components/form-components/textarea/index.tsx
> +    const className = this.props.className || 'lum__text-area'
same

2024-08-07 18:16 UTC, JWebCoder requested changes

2024-08-07 18:16 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/checkbox/index.tsx
> +export class LumCheckbox extends React.Component<ControlLogicProps> {
please use functional components. Same for the rest of the form components.

2024-08-08 09:09 UTC, JWebCoder requested changes
please check the comments

2024-08-08 09:09 UTC, JWebCoder commented on package.json
> -    "@changesets/cli": "^2.27.7"
why was this removed?

2024-08-08 09:09 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/input/index.tsx
> +  const className = `${defaultClass} ${props.className || ''}`
we are using a package called classnames to handle this. Please update the code to use it.

2024-08-08 09:09 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/radio-button/index.tsx
> +  const className = `${defaultClass} ${props.className || ''}`
we are using a package called classnames to handle this. Please update the code to use it.

2024-08-08 09:09 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/slider/index.tsx
> +  const className = `${defaultClass} ${props.className || ''}`
we are using a package called classnames to handle this. Please update the code to use it.

2024-08-08 09:09 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/switch-list/index.tsx
> +  const className = `${defaultClass} ${props.className || ''}`
we are using a package called classnames to handle this. Please update the code to use it.

2024-08-08 09:09 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/textarea/index.tsx
> +  const className = `${defaultClass} ${props.className || ''}`
we are using a package called classnames to handle this. Please update the code to use it.

2024-08-08 09:44 UTC, Felix-by-merkle approved these changes

2024-08-08 09:47 UTC, JWebCoder requested changes
make sure to merge the master into this before merging the pull request.

2024-08-08 09:47 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/demo.tsx
> +          className='lum__checkbox'
Are these classes needed? They are the default values, right? Please remove these or change them to something different from the default. It may confuse in the future.

2024-08-08 09:47 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/demo.tsx
> +          className='lum__slider'
same

2024-08-08 09:47 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/demo.tsx
> +          className='lum__text-area'
same

2024-08-08 09:47 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/demo.tsx
> +          className='lum__radio-button'
same

2024-08-08 09:47 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/demo.tsx
> +          className='lum__input'
same

2024-08-08 09:47 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/demo.tsx
> +          className='lum__switch-list'
same

2024-08-08 09:47 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components/demo.tsx
> +          className='lum__input'
same

2024-08-08 10:37 UTC, JWebCoder approved these changes

2024-08-08 10:37 UTC, merged