feature81 - On hover components button background
Funfunz/lumina-next pull request #37
Opened 2024-08-02 23:20 UTC by AdrianaAC

2024-08-02 23:22 UTC, AdrianaAC commented
![](https://github.trello.services/images/mini-trello-icon.png) [On hover components button background](https://trello.com/c/8RBCkUGC/81-on-hover-components-button-background)

2024-08-05 14:59 UTC, JWebCoder commented
please update the design to be closer to the one from figma

2024-08-05 14:59 UTC, JWebCoder requested changes
please update the design to be closer to the one from figma

2024-08-05 16:28 UTC, miriampereira approved these changes

2024-08-05 16:55 UTC, Felix-by-merkle requested changes

2024-08-06 09:57 UTC, JWebCoder requested changes
review the ticket on trello, we need some fixes to the button colors.

2024-08-06 09:57 UTC, JWebCoder commented on .hintrc
what is this for @AdrianaAC ?

2024-08-06 15:10 UTC, JWebCoder approved these changes

2024-08-06 15:11 UTC, merged