Display options when adding a new component
Funfunz/lumina-next pull request #50
Opened 2024-08-08 12:50 UTC by Felix-by-merkle

**85**

**About**
Displaying the new component options when adding a component

**Changes**
Added the form data to the add modal

**Testing**
N/a

**Screenshot / Gifs**
N/a

**Notes**
No fields are mandatory, needs integration with https://github.com/Funfunz/lumina-next/issues/43

2024-08-08 13:10 UTC, bmirra01 approved these changes

2024-08-08 18:29 UTC, JWebCoder requested changes

2024-08-08 18:29 UTC, JWebCoder commented on packages/lumina-core/src/components/editor-buttons-container/styles.scss
> +*:has(> .showEditContainer) {
There should be no minimum height for the components. Lumina should not affect the component's layout.

2024-08-08 18:29 UTC, JWebCoder commented on packages/lumina-core/src/components/modals/add/index.tsx
> +import { TConfig, getComponentConfig } from '@/main'
import TConfig has a type. import type { TConfig } from '@/main'

2024-08-08 18:29 UTC, JWebCoder commented on packages/lumina-core/src/components/modals/add/index.tsx
> +        <input
All the inputs should be replaced by the new form components. I'll open a new ticket for this.

2024-08-08 18:29 UTC, JWebCoder commented on packages/lumina-core/src/components/modals/add/index.tsx
> +              <LuminaInputRenderer
Same here

2024-08-08 18:29 UTC, JWebCoder commented on packages/lumina-core/src/components/modals/edit/index.tsx
>  import { IComponentProps } from '@/models/data'
This is a type also

2024-08-09 09:29 UTC, Felix-by-merkle commented on packages/lumina-core/src/components/editor-buttons-container/styles.scss
> +*:has(> .showEditContainer) {
ok. there will be confusion when adding a component, because it will be shown on the tree but not on the page, but the documentation needs to be clear about that

2024-08-09 09:30 UTC, Felix-by-merkle commented on packages/lumina-core/src/components/modals/add/index.tsx
> +        <input
in my view that should be a different ticket yes

2024-08-09 14:24 UTC, merged