bugfix/46-fix-edit-icon-on-linkbox-component
Funfunz/lumina-next pull request #60
Opened 2024-08-20 15:35 UTC by bmirra01

Sorted by adding the code "event.preventDefault()" to avoid having the link opening event triggered everytime the button edit and delete is pressed. Also added this fix on Add button in case this is needed in the future for other components.

2024-08-20 15:55 UTC, JWebCoder requested changes

2024-08-20 15:55 UTC, JWebCoder commented on packages/lumina-core/src/components/action-buttons/add/index.tsx
> +  const handleButtonClick = (event: any) => {
Do not use any please.

2024-08-20 15:55 UTC, JWebCoder commented on packages/lumina-core/src/components/action-buttons/delete/index.tsx
> +  const handleToggleDeleteModal = (event: any) => {
Do not use any please.

2024-08-20 15:55 UTC, JWebCoder commented on packages/lumina-core/src/components/action-buttons/edit/index.tsx
> +  const handleToggleEditModal = (event: any) => {
Do not use any please.

2024-08-20 16:06 UTC, bmirra01 commented on packages/lumina-core/src/components/action-buttons/add/index.tsx
> +  const handleButtonClick = (event: any) => {
Replaced it by React.MouseEvent<HTMLButtonElement>

2024-08-20 16:06 UTC, bmirra01 commented on packages/lumina-core/src/components/action-buttons/delete/index.tsx
> +  const handleToggleDeleteModal = (event: any) => {
Replaced it by React.MouseEvent<HTMLButtonElement>

2024-08-20 16:06 UTC, bmirra01 commented on packages/lumina-core/src/components/action-buttons/edit/index.tsx
> +  const handleToggleEditModal = (event: any) => {
Replaced it by React.MouseEvent<HTMLButtonElement>

2024-08-21 07:57 UTC, Felix-by-merkle approved these changes

2024-08-21 09:01 UTC, antonio-rodrigues approved these changes

2024-08-21 09:07 UTC, merged