[WIP] feature/67-change-form-and-form-elements-to-react-hook-form
Funfunz/lumina-next pull request #69
Opened 2024-08-22 11:16 UTC by bmirra01

(Work in Progress)

Currently working on creating the Form components

Done:
Input

In progress:
Checkbox

To Do:
Radio Button
Slider
Switch
TextArea

After that the field validation will be implemented with React Hook Form

2024-08-23 13:39 UTC, bmirra01 commented on packages/lumina-core/src/components/form-components-RHF/input/index.tsx
> +      <br />
Hey, thanks for the heads up, but I think you got this code a bit Outdated eheh, I used <br /> just to test out really quick something and then removed it, on the current code we no longer have that! I totally agreed with you, on CSS I fixed it with display: flex and flex-direction: column, looks fine now!

2024-08-30 09:24 UTC, JWebCoder requested changes
Still needs to have react hook forms attached to it. And it's still missing the validation errors. Please focus on a single component, input for example, once you have it fully done, let's review the pull request again.

2024-08-30 09:24 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components-RHF/input/index.tsx
> +      if (activateEnterPress) {
this logic should not be on the input level

2024-08-30 09:24 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components-RHF/input/index.tsx
> +      if (clearOnEnterPress && inputRef.current) {
this logic should not be on the input level

2024-08-30 09:24 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components-RHF/slider/index.tsx
> +          {cx(rangeValue > 0 ? cx(rangeValue, suffix) : rangeValue)}
what is this for? And why are we using classnames to write text into the screen?

2024-08-30 09:24 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components-RHF/slider/index.tsx
> +  suffix?: '€' | 'km' | 'm'
shouldn't this be just a string? why is it restricted to these values only?

2024-08-30 09:24 UTC, JWebCoder commented on packages/lumina-core/src/components/form-components-RHF/checkbox/index.tsx
> +        {help && <p className={cx('checkbox_container__help', className)}>{help}</p>}
it looks like this is the same on all components. Can this be a component shared between them?

2024-08-30 09:27 UTC, bmirra01 commented on packages/lumina-core/src/components/form-components-RHF/slider/index.tsx
> +          {cx(rangeValue > 0 ? cx(rangeValue, suffix) : rangeValue)}
You are right, my bad, forgot to remove cx, this is to avoid having a suffix if the value is 0 and nothing is showing on the slider

2024-08-30 09:28 UTC, bmirra01 commented on packages/lumina-core/src/components/form-components-RHF/input/index.tsx
> +      if (activateEnterPress) {
where should I move this? What do you suggest? A single component for this? Or any other component? Or just remove this option?

2024-08-30 09:28 UTC, bmirra01 commented on packages/lumina-core/src/components/form-components-RHF/input/index.tsx
> +      if (clearOnEnterPress && inputRef.current) {
where should I move this? What do you suggest? A single component for this? Or any other component? Or just remove this option?

2024-08-30 09:29 UTC, bmirra01 commented on packages/lumina-core/src/components/form-components-RHF/slider/index.tsx
> +  suffix?: '€' | 'km' | 'm'
You are right, I can have this to be a string for the user/dev to pick what the suffix should be

2024-08-30 09:31 UTC, bmirra01 commented on packages/lumina-core/src/components/form-components-RHF/checkbox/index.tsx
> +        {help && <p className={cx('checkbox_container__help', className)}>{help}</p>}
There is just 1 or 2 components that doesn't have the help, but in that case I would have to also do it for the Label, do you want me to do it?

2024-08-30 12:13 UTC, bmirra01 commented on packages/lumina-core/src/components/form-components-RHF/slider/index.tsx
> +          {cx(rangeValue > 0 ? cx(rangeValue, suffix) : rangeValue)}
Sorted

2024-08-30 13:39 UTC, bmirra01 commented on packages/lumina-core/src/components/form-components-RHF/input/index.tsx
> +      if (activateEnterPress) {
I've moved this to an importable custom hook, check the latest commit!

2024-08-30 13:39 UTC, bmirra01 commented on packages/lumina-core/src/components/form-components-RHF/input/index.tsx
> +      if (clearOnEnterPress && inputRef.current) {
I've moved this to an importable custom hook, check the latest commit!

2024-09-02 11:03 UTC, bmirra01 commented
> Still needs to have react hook forms attached to it. And it's still missing the validation errors. Please focus on a single component, input for example, once you have it fully done, let's review the pull request again.

Done a Demo component with the Input having validation. Let me know once you want to check this PR to close it (hopefully!)

2024-09-02 16:56 UTC, bmirra01 commented
@JWebCoder , changes done according to we spoke. Also removed the tests from Sidebar. Left the Demo in the folder in case you want to check something.

2024-09-03 00:21 UTC, JWebCoder approved these changes

2024-09-03 00:21 UTC, merged